### ISSUE TITLE
Tapo plugin not working

### ISSUE THREAD

**Issue by Gilbertonl** [593304/Domoticz-Tapo#4]
Hello, 

If i use the plugin i get this error in the log:

```
2022-10-25 17:09:47.083 Error: Tapo: Traceback (most recent call last):
2022-10-25 17:09:47.083 Error: Tapo: File "/home/pi/domoticz/plugins/Domoticz-Tapo/plugin.py", line 207, in onHeartbeat
2022-10-25 17:09:47.083 Error: Tapo: _plugin.onHeartbeat()
2022-10-25 17:09:47.083 Error: Tapo: File "/home/pi/domoticz/plugins/Domoticz-Tapo/plugin.py", line 142, in onHeartbeat
2022-10-25 17:09:47.083 Error: Tapo: self.heartbeat.beatHeartbeat()
2022-10-25 17:09:47.083 Error: Tapo: File "/home/pi/domoticz/plugins/Domoticz-Tapo/plugin.py", line 44, in beatHeartbeat
2022-10-25 17:09:47.083 Error: Tapo: self.callback()
2022-10-25 17:09:47.083 Error: Tapo: File "/home/pi/domoticz/plugins/Domoticz-Tapo/plugin.py", line 146, in update
2022-10-25 17:09:47.083 Error: Tapo: self.p100.handshake()
2022-10-25 17:09:47.083 Error: Tapo: File "/usr/local/lib/python3.7/dist-packages/PyP100/PyP100.py", line 124, in handshake
2022-10-25 17:09:47.083 Error: Tapo: encryptedKey = r.json()["result"]["key"]
2022-10-25 17:09:47.083 Error: Tapo: KeyError: 'result'

```

**Comment by DrakarBarna** [comment]
This plugin is base on PyP100 and since TP-Link has correct a security vulnerability, the login methode is not working anymore.
The only info I find is to modify this plugin from PyP100 to plugp100 (https://github.com/petretiandrea/plugp100/tree/main).

But I have NO knowledge on Python, so I cannot really help more than that.

**Comment by RandomOutcome** [comment]
Had the same issue with my P100 devices upgrading this week.  To resolve I've ported the  Domoticz-Tapo P100 plugin to plugp100 from PyP100.  I've published the port, which can be be found here https://github.com/RandomOutcome/Domoticz-Tapo-P100-Plugin, in case it helps others.  The port is complete, but has only been tested in my environment.

The plugp100 library requires python3.10 as a minimum, hence if on 3.8 or 3.9 it won't work. I've added a port of plugp100 that supports these two earlier python versions - which can be found here https://github.com/RandomOutcome/plugp100-3.9.  Python versions before 3.8 unfortunately cannot be ported to.
