### ISSUE TITLE
TAPO not working with latest firmware (dec 2023)

### ISSUE THREAD

**Issue by sledgemhammer** [593304/Domoticz-Tapo#5]
As end of year, started updating all hardware that was not update over 12 mnth.
Also TAPO 110 had a firmware update, apperantly the api changed as the do not work anymore with this domoticz plugin.

"Exception occurred during connection to device : KeyError, arguments: ('result',). Next try in 300 seconds"

Can this be fixed somehow ?

**Comment by LacmanHUN** [comment]
Same here, recently bought a P100 and instantly did a FW update to 1.2.1 build 230804 (rel. 190922) during setup in Tapo App.

The result in domoticz:

```
2024-03-04 14:11:53.296 Status: Tapo: Entering work loop.
2024-03-04 14:11:53.297 Status: Tapo: Started.
2024-03-04 14:11:53.896 Status: Tapo: Initialized version 0.2, author '593304'
2024-03-04 14:11:54.738 Error: Tapo: Call to function 'onStart' failed, exception details:
2024-03-04 14:11:54.739 Error: Tapo: Traceback (most recent call last):
2024-03-04 14:11:54.739 Error: Tapo: File "/home/lacman/domoticz/plugins/Domoticz-Tapo/plugin.py", line 179, in onStart
2024-03-04 14:11:54.739 Error: Tapo: _plugin.onStart()
2024-03-04 14:11:54.739 Error: Tapo: File "/home/lacman/domoticz/plugins/Domoticz-Tapo/plugin.py", line 74, in onStart
2024-03-04 14:11:54.739 Error: Tapo: self.update(False)
2024-03-04 14:11:54.739 Error: Tapo: File "/home/lacman/domoticz/plugins/Domoticz-Tapo/plugin.py", line 146, in update
2024-03-04 14:11:54.739 Error: Tapo: self.p100.handshake()
2024-03-04 14:11:54.739 Error: Tapo: File "/usr/local/lib/python3.9/dist-packages/PyP100/PyP100.py", line 129, in handshake
2024-03-04 14:11:54.739 Error: Tapo: encryptedKey = r.json()["result"]["key"]
2024-03-04 14:11:54.739 Error: Tapo: KeyError: 'result'
```


Looking forward for the adjustment in the script, if it's possible.
Thanks in advance!
